---
clickhouse:
  hosts:
    clickhouse-01:
      ansible_host: 51.250.91.75 
      ansible_user: ubuntu

vector:
  hosts:
    vector-01:
      ansible_host: 158.160.33.246
      ansible_user: ubuntu 

lighthouse:
  hosts:
    lighthouse-01:
      ansible_host: 51.250.10.132
      ansible_user: ubuntu 
